# mkdocs.yml
site_name: "Inspeqtor"
site_url: https://porametpat.github.io/inspeqtor/
site_author: Poramet Pathumsoot
site_description: >-
  A Data-Efficient Framework for Characterizing and Calibrating That Squeezes Every Bit of Information from Quantum Devices.

watch:
    - src/inspeqtor
    - docs/

theme:
    name: material
    logo: assets/inspeqtor_logo.svg
    favicon: assets/inspeqtor_logo_square.svg
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
          primary: white
          accent: pink

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
          primary: black
          accent: pink
    features:
        - content.code.copy
        - content.tabs.link

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/PorametPat/inspeqtor

plugins:
    - search
    - social
    - mkdocstrings:
          handlers:
              python:
                  options:
                      members_order: source
                      show_bases: false
                      show_root_heading: true
                      show_signature_annotations: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      parameter_headings: false
                      show_signature: true
                      separate_signature: true
                      signature_crossrefs: true
    - mkdocs-jupyter:
          remove_tag_config:
              remove_input_tags:
                  - hide_code

markdown_extensions:
    - admonition
    - pymdownx.snippets:
          base_path:
              - docs
    - pymdownx.highlight:
          use_pygments: true
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Getting start: index.md
    - Tutorials:
          - Overviews: tutorials/overviews.md
          - Generate dataset: tutorials/tutorial_0001_dataset.ipynb
          - Generate dataset v2: tutorials/tutorial_0001_dataset_v2.ipynb
          - C&C: tutorials/tutorial_0003_cc.ipynb
          - Control Action: tutorials/tutorial_0002_control.ipynb
    - explanation.md
    - How-To Guides:
          - Generate dataset: guides/generate-dataset.md
          - Working memory: guides/working_memory.ipynb
          - Converting DNN to BNN: guides/dnn_to_bnn.ipynb
          - Bayesian Optimization: guides/bayesian_optimization.ipynb

    - API Reference:
          - Guide: api-reference.md
          - experimental:
            - utils: api/experimental/utils.md
            - models:
                    - linen: api/experimental/linen.md
                    - nnx: api/experimental/nnx.md
            - data: api/experimental/data.md
            - constant: api/experimental/constant.md
            - control: api/experimental/control.md
            - optimize: api/experimental/optimize.md
            - physics: api/experimental/physics.md
            - predefined: api/experimental/predefined.md
            - probabilistic: api/experimental/probabilistic.md
            - visualization: api/experimental/visualization.md
          - v2:
            - data: api/v2/data.md
            - control: api/v2/control.md
            - utils: api/v2/utils.md
            - optimize: api/v2/optimize.md
            - predefined: api/v2/predefined.md
    - Developer Guide: 
        - Note: dev.md
        - Temporary Directory: developer/note_tempfile.ipynb
